name: Deploy automatico ingressos

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: "nadoutti"
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: nadoutti/gateway-zambom:${{ github.sha }}

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_TEST }}
          username: "ubuntu"
          key: ${{ secrets.KEY_TEST }}
          port: 22
          script: |
            docker stop gateway-zambom
            docker rm --force gateway-zambom
            docker run  -d -p 8082:8004 -e SUPABASE_URL=${{ secrets.SUPABASE_URL }} -e SUPABASE_KEY=${{ secrets.SUPABASE_KEY }} -e USUARIOS_SERVICE_URL=${{ secrets.USUARIOS_SERVICE_URL }} -e EVENTOS_SERVICE_URL=${{ secrets.EVENTOS_SERVICE_URL }} --network=rede --name gateway-zambom nadoutti/gateway-zambom:${{ github.sha }}
